# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    teacher:
        class: AppBundle\Model\TeachersManager
        arguments:  ["@doctrine", "@service_container"]
    pupil:
        class: AppBundle\Model\PupilsManager
        arguments:  ["@doctrine", "@service_container"]
    pupilsDao:
        class: AppBundle\Model\PupilsDao
        arguments:  ["@doctrine"]
    teachersDao:
        class: AppBundle\Model\TeachersDao
        arguments:  ["@doctrine"]
    teacherPupilsDao:
        class: AppBundle\Model\TeacherPupilsDao
        arguments:  ["@doctrine"]